showNewVersionIcon: true
hideAfterStartup: false
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: true
connShowProcess: true
showTrayProxyDelayIndicator: true
theme: 1
randomMixedPort: false
shortcutTun: ""
systemTheme: false
useSystemEmoji: true
